In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('spam.csv')

In [3]:
df.head(5)

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
#cleaning

In [4]:
df.isnull().sum()

Category    0
Message     0
dtype: int64

In [5]:
df.duplicated().sum()

415

In [6]:
df = df.drop_duplicates(keep='first')

In [5]:
df.Category.unique()

array(['ham', 'spam'], dtype=object)

In [7]:
df['spam']=df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [8]:
df.head(5)

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.Message,df.spam,test_size=0.2,random_state=42)

In [10]:
x_train

1978    Reply to win £100 weekly! Where will the 2006 ...
3989    Hello. Sort of out in town already. That . So ...
3935     How come guoyang go n tell her? Then u told her?
4078    Hey sathya till now we dint meet not even a si...
4086    Orange brings you ringtones from all time Char...
                              ...                        
3772    Hi, wlcome back, did wonder if you got eaten b...
5191                               Sorry, I'll call later
5226        Prabha..i'm soryda..realy..frm heart i'm sory
5390                           Nt joking seriously i told
860               Did he just say somebody is named tampa
Name: Message, Length: 4457, dtype: object

In [11]:
len(x_train)

4457

In [12]:
len(x_test)

1115

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
cv_messages = v.fit_transform(x_train.values)
cv_messages.toarray()[0:5]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [15]:
cv_messages

<4457x7701 sparse matrix of type '<class 'numpy.int64'>'
	with 59275 stored elements in Compressed Sparse Row format>

In [16]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()

In [17]:
model.fit(cv_messages,y_train)

MultinomialNB()

In [20]:
email = {
    "upto 10% discount on parking, exclusive offer for you. Dont miss this reward!",
    "okay lar joking.. wif u oni..."
}
email_count = v.transform(email)
model.predict(email_count)

array([1, 0], dtype=int64)

In [21]:
x_test_count = v.transform(x_test)
model.score(x_test_count,y_test)

0.9919282511210762

In [23]:
from sklearn.pipeline import Pipeline
clf = Pipeline( [
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
]
)
clf.fit(x_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [24]:
email = {
    "upto 10% discount on parking, exclusive offer for you. Dont miss this reward!",
    "okay lar joking.. wif u oni..."
}
clf.predict(email)

array([1, 0], dtype=int64)

In [25]:
clf.score(x_test,y_test)

0.9919282511210762

In [26]:
import joblib
joblib.dump(clf,'spam_detect_model.pkl')

['spam_detect_model.pkl']

In [27]:
#our model is complete